// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkhs06R0V1kSE8yrWwRbNGmf0Qn1-C1mI',
    appId: '1:562908988729:web:46c2273d005f0f584494e8',
    messagingSenderId: '562908988729',
    projectId: 'emart23',
    authDomain: 'emart23.firebaseapp.com',
    storageBucket: 'emart23.appspot.com',
    measurementId: 'G-50KB8NBKZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf21PwMEhJp0qu_LuK2AtKEXk7T3QT-qQ',
    appId: '1:562908988729:android:1720414542172b034494e8',
    messagingSenderId: '562908988729',
    projectId: 'emart23',
    storageBucket: 'emart23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEYm-OqKbonkYytETcWZUQ-jF_RyUF6lw',
    appId: '1:562908988729:ios:e26325e2616c14a74494e8',
    messagingSenderId: '562908988729',
    projectId: 'emart23',
    storageBucket: 'emart23.appspot.com',
    iosBundleId: 'com.example.emartApp2023BaabaDevs1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEYm-OqKbonkYytETcWZUQ-jF_RyUF6lw',
    appId: '1:562908988729:ios:81ecd5f380138f1b4494e8',
    messagingSenderId: '562908988729',
    projectId: 'emart23',
    storageBucket: 'emart23.appspot.com',
    iosBundleId: 'com.example.emartApp2023BaabaDevs1.RunnerTests',
  );
}
